beg_chinese_lesson_1:
    file_name: "/../../../../data/cedict/tags/books/beg_chinese_lesson1.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Beg Chinese Lesson 1"
    tag_type: ""
    short_name: "BegChineseLesson1"
    description: "Begging Chinese Lesson Part 1"      
    source: "Space separated File"                          
    source_name: "beg_chinese_lesson1.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    
beg_chinese_lesson_2:
    file_name: "/../../../../data/cedict/tags/books/beg_chinese_lesson2.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Beg Chinese Lesson 2"
    tag_type: ""
    short_name: "BegChineseLesson2"
    description: "Begging Chinese Lesson Part 2"      
    source: "Space separated File"                          
    source_name: "beg_chinese_lesson2.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    
beg_chinese_lesson_3:
    file_name: "/../../../../data/cedict/tags/books/beg_chinese_lesson3.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Beg Chinese Lesson 3"
    tag_type: ""
    short_name: "BegChineseLesson3"
    description: "Begging Chinese Lesson Part 3"      
    source: "Space separated File"                          
    source_name: "beg_chinese_lesson3.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    
beg_chinese_lesson_4:
    file_name: "/../../../../data/cedict/tags/books/beg_chinese_lesson4.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Beg Chinese Lesson 4"
    tag_type: ""
    short_name: "BegChineseLesson4"
    description: "Begging Chinese Lesson Part 4"      
    source: "Space separated File"                          
    source_name: "beg_chinese_lesson4.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    
beg_chinese_lesson_5:
    file_name: "/../../../../data/cedict/tags/books/beg_chinese_lesson5.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Beg Chinese Lesson 5"
    tag_type: ""
    short_name: "BegChineseLesson5"
    description: "Begging Chinese Lesson Part 5"      
    source: "Space separated File"                          
    source_name: "beg_chinese_lesson5.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    
beg_chinese_lesson_6:
    file_name: "/../../../../data/cedict/tags/books/beg_chinese_lesson6.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Beg Chinese Lesson 6"
    tag_type: ""
    short_name: "BegChineseLesson6"
    description: "Begging Chinese Lesson Part 6"      
    source: "Space separated File"                          
    source_name: "beg_chinese_lesson6.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    
beg_chinese_lesson_7:
    file_name: "/../../../../data/cedict/tags/books/beg_chinese_lesson7.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Beg Chinese Lesson 7"
    tag_type: ""
    short_name: "BegChineseLesson7"
    description: "Begging Chinese Lesson Part 7"      
    source: "Space separated File"                          
    source_name: "beg_chinese_lesson7.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    
beg_chinese_lesson_8:
    file_name: "/../../../../data/cedict/tags/books/beg_chinese_lesson8.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Beg Chinese Lesson 8"
    tag_type: ""
    short_name: "BegChineseLesson8"
    description: "Begging Chinese Lesson Part 8"      
    source: "Space separated File"                          
    source_name: "beg_chinese_lesson8.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    
beg_chinese_lesson_9:
    file_name: "/../../../../data/cedict/tags/books/beg_chinese_lesson9.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Beg Chinese Lesson 9"
    tag_type: ""
    short_name: "BegChineseLesson9"
    description: "Begging Chinese Lesson Part 9"      
    source: "Space separated File"                          
    source_name: "beg_chinese_lesson9.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    
beg_chinese_lesson_10:
    file_name: "/../../../../data/cedict/tags/books/beg_chinese_lesson10.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Beg Chinese Lesson 10"
    tag_type: ""
    short_name: "BegChineseLesson10"
    description: "Begging Chinese Lesson Part 10"      
    source: "Space separated File"                          
    source_name: "beg_chinese_lesson10.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
