frequency_fict_01:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-01.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 01"
    tag_type: ""
    short_name: "bigram-fict-01"
    description: "Common Fiction Bigrams (2 character words), 1-100"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-01.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_02:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-02.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 02"
    tag_type: ""
    short_name: "bigram-fict-02"
    description: "Common Fiction Bigrams (2 character words), 201-300"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-02.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_03:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-03.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 03"
    tag_type: ""
    short_name: "bigram-fict-03"
    description: "Common Fiction Bigrams (2 character words), 301-400"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-03.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_04:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-04.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 04"
    tag_type: ""
    short_name: "bigram-fict-04"
    description: "Common Fiction Bigrams (2 character words), 401-500"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-04.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_05:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-05.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 05"
    tag_type: ""
    short_name: "bigram-fict-05"
    description: "Common Fiction Bigrams (2 character words), 501-600"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-05.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_06:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-06.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 06"
    tag_type: ""
    short_name: "bigram-fict-06"
    description: "Common Fiction Bigrams (2 character words), 601-700"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-06.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_07:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-07.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 07"
    tag_type: ""
    short_name: "bigram-fict-07"
    description: "Common Fiction Bigrams (2 character words), 701-800"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-07.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_08:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-08.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 08"
    tag_type: ""
    short_name: "bigram-fict-08"
    description: "Common Fiction Bigrams (2 character words), 801-900"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-08.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_09:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-09.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 09"
    tag_type: ""
    short_name: "bigram-fict-09"
    description: "Common Fiction Bigrams (2 character words), 901-1000"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-09.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_10:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-10.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 10"
    tag_type: ""
    short_name: "bigram-fict-10"
    description: "Common Fiction Bigrams (2 character words), 1001-1100"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-10.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_11:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-11.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 11"
    tag_type: ""
    short_name: "bigram-fict-11"
    description: "Common Fiction Bigrams (2 character words), 1101-1200"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-11.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_12:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-12.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 12"
    tag_type: ""
    short_name: "bigram-fict-12"
    description: "Common Fiction Bigrams (2 character words), 1201-1300"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-12.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_13:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-13.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 13"
    tag_type: ""
    short_name: "bigram-fict-13"
    description: "Common Fiction Bigrams (2 character words), 1301-1400"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-13.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_14:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-14.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 14"
    tag_type: ""
    short_name: "bigram-fict-14"
    description: "Common Fiction Bigrams (2 character words), 1401-1500"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-14.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_15:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-15.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 15"
    tag_type: ""
    short_name: "bigram-fict-15"
    description: "Common Fiction Bigrams (2 character words), 1501-1600"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-15.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_16:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-16.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 16"
    tag_type: ""
    short_name: "bigram-fict-16"
    description: "Common Fiction Bigrams (2 character words), 1601-1700"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-16.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_17:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-17.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 17"
    tag_type: ""
    short_name: "bigram-fict-17"
    description: "Common Fiction Bigrams (2 character words), 1701-1800"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-17.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_18:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-18.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 18"
    tag_type: ""
    short_name: "bigram-fict-18"
    description: "Common Fiction Bigrams (2 character words), 1801-1900"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-18.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_19:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-19.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 19"
    tag_type: ""
    short_name: "bigram-fict-19"
    description: "Common Fiction Bigrams (2 character words), 1901-2000"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-19.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
frequency_fict_20:
    file_name: "frequency/jun-da-frequency-bigrams/bigram-fict-20.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "WordListParser"
    entry_type: "BigramEntry"
    tag_name: "Fiction Bigrams 20"
    tag_type: ""
    short_name: "bigram-fict-20"
    description: "Common Fiction Bigrams (2 character words), 2001-2100"
    source: "Jun Da, http://lingua.mtsu.edu/chinese-computing/"            
    source_name: "bigram-fict-20.txt"
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    contains_priority_words: 1
