tags_800_beginner:
    # File name of the source
    file_name: "/../../../../data/cedict/tags/800+800020100915-beginner.csv"
    
    # Boolean whether this tag importer will output
    # some info to a file. (true==>1, false==>0)
    file_dump_trace: 1
    
    # File related metadata
    # Class used for importing the data to the database
    file_importer: "TagImporter"
        
    # Class used for parsing and reading the data into memory
    file_parser: "CSVParser"
    # Not used yet
    file_tolerance: "tone"          
    
    # User-readible name for the tag
    tag_name: "800+ Beginner"
    tag_type: ""
    
    # Database tag_staging table column related
    # System-readible tag name
    short_name: "800Words+Beginner"
    
    # Description of the tag
    description: "800+ Words for beginner"      
    
    # Source of the file
    source: "CSV File"                          
    
    # Source file name
    source_name: "800+800020100915-beginner.csv"     
    
    # Tag should be visible
    visible: 1                                  

    parent_tag_id: 0
    force_off: 0
    
tags_800_intermediate:
    file_name: "/../../../../data/cedict/tags/800+800020100915-mid.csv"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "CSVParser"
    tag_name: "800+ Intermediate"
    tag_type: ""
    short_name: "800Words+Mid"
    description: "800+ Words for Intermediate user"      
    source: "CSV File"                          
    source_name: "800+800020100915-mid.csv"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0

tags_800_advance:
    file_name: "/../../../../data/cedict/tags/800+800020100915-adv.csv"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "CSVParser"
    tag_name: "800+ Advance"
    tag_type: ""
    short_name: "800Words+Advance"
    description: "800+Advanced Words"      
    source: "CSV File"                          
    source_name: "800+800020100915-adv.csv"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
    
tag_800_test_file_small:
    file_name: "/../../../../data/cedict/tags/test_800+800020100915.csv"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "CSVParser"
    tag_name: "800+ Sample"
    tag_type: ""
    short_name: "800Words+SampleTag"
    description: "800+ Words for testing purposes"      
    source: "CSV File"                          
    source_name: "test_800+800020100915.csv"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
