frequency_1:
    file_name: "/../../../../data/cedict/tags/frequency/frequency_list_1-100.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Frequent Words 1-100"
    tag_type: ""
    short_name: "frequency-1-100"
    description: "Frequent Words List 1-100"      
    source: "Space separated File"                          
    source_name: "frequency_list_1-100.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
frequency_2:
    file_name: "/../../../../data/cedict/tags/frequency/frequency_list_101-200.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Frequent Words 101-200"
    tag_type: ""
    short_name: "frequency-101-200"
    description: "Frequent Words List 101-200"      
    source: "Space separated File"                          
    source_name: "frequency_list_101-200.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
frequency_3:
    file_name: "/../../../../data/cedict/tags/frequency/frequency_list_201-300.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Frequent Words 201-300"
    tag_type: ""
    short_name: "frequency-201-300"
    description: "Frequent Words List 201-300"      
    source: "Space separated File"                          
    source_name: "frequency_list_201-300.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
frequency_4:
    file_name: "/../../../../data/cedict/tags/frequency/frequency_list_301-400.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Frequent Words 301-400"
    tag_type: ""
    short_name: "frequency-301-400"
    description: "Frequent Words List 301-400"      
    source: "Space separated File"                          
    source_name: "frequency_list_301-400.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
frequency_5:
    file_name: "/../../../../data/cedict/tags/frequency/frequency_list_401-500.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Frequent Words 401-500"
    tag_type: ""
    short_name: "frequency-401-500"
    description: "Frequent Words List 401-500"      
    source: "Space separated File"                          
    source_name: "frequency_list_401-500.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
frequency_6:
    file_name: "/../../../../data/cedict/tags/frequency/frequency_list_501-600.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Frequent Words 501-600"
    tag_type: ""
    short_name: "frequency-501-600"
    description: "Frequent Words List 501-600"      
    source: "Space separated File"                          
    source_name: "frequency_list_501-600.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
frequency_7:
    file_name: "/../../../../data/cedict/tags/frequency/frequency_list_601-700.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Frequent Words 601-700"
    tag_type: ""
    short_name: "frequency-601-700"
    description: "Frequent Words List 601-700"      
    source: "Space separated File"                          
    source_name: "frequency_list_601-700.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0