schaums_direction:
    file_name: "/../../../../data/cedict/tags/books/schaums/ASKING FOR DIRECTIONS.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Asking For Directions"
    tag_type: ""
    short_name: "schaums_direction"
    description: "Schaums  (Asking For Directions)"      
    source: "Space separated File"                          
    source_name: "ASKING FOR DIRECTIONS.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_home:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT HOME.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At Home"
    tag_type: ""
    short_name: "schaums_home"
    description: "Schaums  (At Home)"      
    source: "Space separated File"                          
    source_name: "AT HOME.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_airport:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT THE AIRPORT.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At the Airport"
    tag_type: ""
    short_name: "schaums_airport"
    description: "Schaums  (At The Airport)"      
    source: "Space separated File"                          
    source_name: "AT THE AIRPORT.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_bank:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT THE BANK.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At The Bank"
    tag_type: ""
    short_name: "schaums_bank"
    description: "Schaums  (At The Bank)"      
    source: "Space separated File"                          
    source_name: "AT THE BANK.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_clothing_store:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT THE CLOTHING STORE.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At The Clothing Store"
    tag_type: ""
    short_name: "schaums_clothing_store"
    description: "Schaums  (At The Clothing Store)"      
    source: "Space separated File"                          
    source_name: "AT THE CLOTHING STORE.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_dry_cleaner:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT THE DRY CLEANER.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At The Dry Cleaner"
    tag_type: ""
    short_name: "schaums_dry_cleaner"
    description: "Schaums  (At The Dry Cleaner)"      
    source: "Space separated File"                          
    source_name: "AT THE DRY CLEANER.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_hospital:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT THE HOSPITAL.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At The Hospital"
    tag_type: ""
    short_name: "schaums_hospital"
    description: "Schaums  (At The Hospital)"      
    source: "Space separated File"                          
    source_name: "AT THE HOSPITAL.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_hotel:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT THE HOTEL.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At The Hotel"
    tag_type: ""
    short_name: "schaums_hotel"
    description: "Schaums  (At The Hotel)"      
    source: "Space separated File"                          
    source_name: "AT THE HOTEL.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_post_office:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT THE POST OFFICE.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At The Post Office"
    tag_type: ""
    short_name: "schaums_post_office"
    description: "Schaums  (At The Post Office)"      
    source: "Space separated File"                          
    source_name: "AT THE POST OFFICE.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_restaurant:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT THE RESTAURANT.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At The Restaurant"
    tag_type: ""
    short_name: "schaums_restaurant"
    description: "Schaums  (At The Restaurant)"      
    source: "Space separated File"                          
    source_name: "AT THE RESTAURANT.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_movies:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT THE THEATER AND THE MOVIES.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At The Theater and The Movies"
    tag_type: ""
    short_name: "schaums_movies"
    description: "Schaums  (At The Theater and The Movies)"      
    source: "Space separated File"                          
    source_name: "AT THE THEATER AND THE MOVIES.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_train_station:
    file_name: "/../../../../data/cedict/tags/books/schaums/AT THE TRAIN STATION.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "At The Train Station"
    tag_type: ""
    short_name: "schaums_train_station"
    description: "Schaums  (At The Train Station)"      
    source: "Space separated File"                          
    source_name: "AT THE TRAIN STATION.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_business:
    file_name: "/../../../../data/cedict/tags/books/schaums/BUSINESS.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Business"
    tag_type: ""
    short_name: "schaums_business"
    description: "Schaums  (Business)"      
    source: "Space separated File"                          
    source_name: "BUSINESS.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_computer:
    file_name: "/../../../../data/cedict/tags/books/schaums/COMPUTER AND INTERNET.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Computer And Internet"
    tag_type: ""
    short_name: "schaums_computer"
    description: "Schaums  (Computer And Internet)"      
    source: "Space separated File"                          
    source_name: "COMPUTER AND INTERNET.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_education:
    file_name: "/../../../../data/cedict/tags/books/schaums/EDUCATION.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Education"
    tag_type: ""
    short_name: "schaums_education"
    description: "Schaums  (Education)"      
    source: "Space separated File"                          
    source_name: "EDUCATION.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_phone_call:
    file_name: "/../../../../data/cedict/tags/books/schaums/MAKING A PHONE CALL.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Making A Phone Call"
    tag_type: ""
    short_name: "schaums_phone_call"
    description: "Schaums  (Making A Phone Call)"      
    source: "Space separated File"                          
    source_name: "MAKING A PHONE CALL.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_airplane:
    file_name: "/../../../../data/cedict/tags/books/schaums/ON THE AIRPLANE.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "On The Airplane"
    tag_type: ""
    short_name: "schaums_airplane"
    description: "Schaums  (On The Airplane)"      
    source: "Space separated File"                          
    source_name: "ON THE AIRPLANE.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_customs:
    file_name: "/../../../../data/cedict/tags/books/schaums/PASSPORT CONTROL AND CUSTOMS.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Passport Control and Customs"
    tag_type: ""
    short_name: "schaums_customs"
    description: "Schaums  (Passport Control And Customs)"      
    source: "Space separated File"                          
    source_name: "PASSPORT CONTROL AND CUSTOMS.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_transport:
    file_name: "/../../../../data/cedict/tags/books/schaums/PUBLIC TRANSPORTATION.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Public Transportation"
    tag_type: ""
    short_name: "schaums_transport"
    description: "Schaums  (Public Transportation)"      
    source: "Space separated File"                          
    source_name: "PUBLIC TRANSPORTATION.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_shop_food:
    file_name: "/../../../../data/cedict/tags/books/schaums/SHOPPING FOR FOOD.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Shopping For Food"
    tag_type: ""
    short_name: "schaums_shop_food"
    description: "Schaums  (Shopping For Food)"      
    source: "Space separated File"                          
    source_name: "SHOPPING FOR FOOD.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_sports:
    file_name: "/../../../../data/cedict/tags/books/schaums/SPORTS.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "Sports"
    tag_type: ""
    short_name: "schaums_sports"
    description: "Schaums  (Sports)"      
    source: "Space separated File"                          
    source_name: "SPORTS.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_automobile:
    file_name: "/../../../../data/cedict/tags/books/schaums/THE AUTOMOBILE.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "The Automobile"
    tag_type: ""
    short_name: "schaums_automobile"
    description: "Schaums  (The Automobile)"      
    source: "Space separated File"                          
    source_name: "THE AUTOMOBILE.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
schaums_weather:
    file_name: "/../../../../data/cedict/tags/books/schaums/THE WEATHER.txt"
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_parser: "BookListParser"
    tag_name: "The Weather"
    tag_type: ""
    short_name: "schaums_weather"
    description: "Schaums  (The Weather)"      
    source: "Space separated File"                          
    source_name: "THE WEATHER.txt"     
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0