starred:    
    file_dump_trace: 1
    file_importer: "TagImporter"
    tag_name: "My Starred Words"
    tag_type: ""
    entry_type: "CSVEntry"
    short_name: "starred_words"
    description: "Words you've starred in Search and Study will appear here."      
    source: "system_tags"                          
    source_name: "system_tags"     
    editable: 1
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
lwe_favs:
    file_dump_trace: 1
    file_importer: "TagImporter"
    file_name: "/../../../../data/cedict/tags/lwe_favorites.txt"
    file_parser: "WordListParser"
    entry_type: "CSVEntry"
    tag_name: "Long Weekend Favorites"
    tag_type: ""
    short_name: "lwe_favs"
    description: "Long Weekend Favorites"      
    source: "system_tags"                          
    source_name: "system_tags"     
    editable: 1
    visible: 1                                  
    parent_tag_id: 0
    force_off: 0
