defaults:
  ttl: 1800
  readonly: false
  urlencode: false
  c_threshold: 10000
  compression: true
  debug: false
  namespace: npedia
  sessions: true
  session_servers: false
  fragments: true
  memory: 128
  servers: localhost:11211
  benchmarking: true
  raise_errors: true
  fast_hash: false
  fastest_hash: false

development:
  sessions: false
  fragments: false
  servers: localhost:11211

# turn off caching
test: 
  disabled: true

production:
  ttl: 1800
  readonly: false
  urlencode: false
  c_threshold: 10000
  compression: true
  debug: false
  namespace: npedia
  sessions: true
  session_servers: false
  fragments: true
  memory: 256
  servers: localhost:11211
  benchmarking: true
  raise_errors: true
  fast_hash: false
  fastest_hash: false
#  memory: 256
#  benchmarking: false
#  servers:
#    - 192.185.254.121:11211
#    - 192.185.254.138:11211
#    - 192.185.254.160:11211
