--- 
- 0: 
    added: 177
    removed: 0
    changed: 0
    date: 2011-12-22 02:21:05 +11:00
    filename: test_data/test_diff_cedict_old.u8
- 1: 
    added: 23
    changed: 17
    removed: 7
    date: 2011-12-22T02:21:05+11:00
    filename: test_data/test_diff_cedict_new.u8
