# The root of the group
# Which has the name on beginning of its 
# element.
# Followed by another group or tag
# Differentiated by the structure. 
# Each Tag will be structured like file_name and key for its dictionary
# Each Group will be structured with 
study_sets:
    name: "Study Sets"
    hsk:
        # 1 Means recommended = true
        name: ["HSK Level 1~6", 1]
        hsk_1:
            file: "hsk_config.yml"
            metadata_key: "hsk_1"
        hsk_2:
            file: "hsk_config.yml"
            metadata_key: "hsk_2"
        hsk_3:
            file: "hsk_config.yml"
            metadata_key: "hsk_3"
        hsk_4:
            file: "hsk_config.yml"
            metadata_key: "hsk_4"
        hsk_5:
            file: "hsk_config.yml"
            metadata_key: "hsk_5"
        hsk_6:
            file: "hsk_config.yml"
            metadata_key: "hsk_6"
    tocfl_800_words:
        # 1 Means recommended = true
        name: ["TOCFL Level 1~3 (Taiwan)", 1]
        800_1_beginner: 
            file: "file_800_config.yml"
            metadata_key: "tags_800_1_beginner"
        800_2_intermediate:
            file: "file_800_config.yml"
            metadata_key: "tags_800_2_intermediate"
        800_3_advance:
            file: "file_800_config.yml"
            metadata_key: "tags_800_3_advance"
    books:
        name: ["Textbook Lessons", 0]
        beg_chinese_lesson:
            name: "Beginner's Chinese (Yong Ho)"
            beg_chinese_lesson_01:
                file: "beg_chinese_config.yml"
                metadata_key: "beg_chinese_lesson_1"
            beg_chinese_lesson_02:
                file: "beg_chinese_config.yml"
                metadata_key: "beg_chinese_lesson_2"
            beg_chinese_lesson_03:
                file: "beg_chinese_config.yml"
                metadata_key: "beg_chinese_lesson_3"
            beg_chinese_lesson_04:
                file: "beg_chinese_config.yml"
                metadata_key: "beg_chinese_lesson_4"
            beg_chinese_lesson_05:
                file: "beg_chinese_config.yml"
                metadata_key: "beg_chinese_lesson_5"
            beg_chinese_lesson_06:
                file: "beg_chinese_config.yml"
                metadata_key: "beg_chinese_lesson_6"
            beg_chinese_lesson_07:
                file: "beg_chinese_config.yml"
                metadata_key: "beg_chinese_lesson_7"
            beg_chinese_lesson_08:
                file: "beg_chinese_config.yml"
                metadata_key: "beg_chinese_lesson_8"
            beg_chinese_lesson_09:
                file: "beg_chinese_config.yml"
                metadata_key: "beg_chinese_lesson_9"
            beg_chinese_lesson_10:
                file: "beg_chinese_config.yml"
                metadata_key: "beg_chinese_lesson_10"
        colloqial_chinese_lesson:
            name: "Colloquial Chinese (P.C. T'ung, D.E. Pollard)"
            col_chinese_lesson_01:
                file: "colloqial_chinese_config.yml"
                metadata_key: "colloquial_chinese_lesson_1"
            col_chinese_lesson_02:
                file: "colloqial_chinese_config.yml"
                metadata_key: "colloquial_chinese_lesson_2"
            col_chinese_lesson_03:
                file: "colloqial_chinese_config.yml"
                metadata_key: "colloquial_chinese_lesson_3"
            col_chinese_lesson_04:
                file: "colloqial_chinese_config.yml"
                metadata_key: "colloquial_chinese_lesson_4"
            col_chinese_lesson_05:
                file: "colloqial_chinese_config.yml"
                metadata_key: "colloquial_chinese_lesson_5"
            col_chinese_lesson_06:
                file: "colloqial_chinese_config.yml"
                metadata_key: "colloquial_chinese_lesson_6"
            col_chinese_lesson_07:
                file: "colloqial_chinese_config.yml"
                metadata_key: "colloquial_chinese_lesson_7"
            col_chinese_lesson_08:
                file: "colloqial_chinese_config.yml"
                metadata_key: "colloquial_chinese_lesson_8"
            col_chinese_lesson_09:
                file: "colloqial_chinese_config.yml"
                metadata_key: "colloquial_chinese_lesson_9"
            col_chinese_lesson_10:
                file: "colloqial_chinese_config.yml"
                metadata_key: "colloquial_chinese_lesson_10"
        integrated_chinese:
            name: "Integrated Chinese, 2nd Ed. (Tao-chung Yao, Yuehua Liu)"
            ic_intro_dates_and_time:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_intro_date_and_time"
            ic_intro_numbers:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_intro_numbers"
            ic_intro_radicals:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_intro_radicals"
            ic_lesson_01:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_1"
            ic_lesson_02:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_2"
            ic_lesson_03:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_3"
            ic_lesson_04:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_4"
            ic_lesson_05:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_5"
            ic_lesson_06:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_6"
            ic_lesson_07:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_7"
            ic_lesson_08:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_8"
            ic_lesson_09:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_9"
            ic_lesson_10:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_10"
            ic_lesson_11:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_11"
            ic_lesson_12:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_12"
            ic_lesson_13:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_13"
            ic_lesson_14:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_14"
            ic_lesson_15:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_15"
            ic_lesson_16:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_16"
            ic_lesson_17:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_17"
            ic_lesson_18:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_18"
            ic_lesson_19:
                file: "integrated_chinese_combined_config.yml"
                metadata_key: "ic_19"
        pcr:
            name: "Practical Chinese Reader, Book I"
            pcr_01_5:
                file: "pcr_config.yml"
                metadata_key: "pcr_1_5"
            pcr_06:
                file: "pcr_config.yml"
                metadata_key: "pcr_6"
            pcr_07:
                file: "pcr_config.yml"
                metadata_key: "pcr_7"
            pcr_08:
                file: "pcr_config.yml"
                metadata_key: "pcr_8"
            pcr_09:
                file: "pcr_config.yml"
                metadata_key: "pcr_9"
            pcr_10:
                file: "pcr_config.yml"
                metadata_key: "pcr_10"
            pcr_11:
                file: "pcr_config.yml"
                metadata_key: "pcr_11"
            pcr_12:
                file: "pcr_config.yml"
                metadata_key: "pcr_12"
            pcr_13:
                file: "pcr_config.yml"
                metadata_key: "pcr_13"
            pcr_14:
                file: "pcr_config.yml"
                metadata_key: "pcr_14"
            pcr_15:
                file: "pcr_config.yml"
                metadata_key: "pcr_15"
            pcr_16:
                file: "pcr_config.yml"
                metadata_key: "pcr_16"
            pcr_17:
                file: "pcr_config.yml"
                metadata_key: "pcr_17"
            pcr_18:
                file: "pcr_config.yml"
                metadata_key: "pcr_18"
            pcr_19:
                file: "pcr_config.yml"
                metadata_key: "pcr_19"
            pcr_20:
                file: "pcr_config.yml"
                metadata_key: "pcr_20"
            pcr_21:
                file: "pcr_config.yml"
                metadata_key: "pcr_21"
            pcr_22:
                file: "pcr_config.yml"
                metadata_key: "pcr_22"
            pcr_23:
                file: "pcr_config.yml"
                metadata_key: "pcr_23"
            pcr_24:
                file: "pcr_config.yml"
                metadata_key: "pcr_24"
            pcr_25:
                file: "pcr_config.yml"
                metadata_key: "pcr_25"
            pcr_26:
                file: "pcr_config.yml"
                metadata_key: "pcr_26"
            pcr_27:
                file: "pcr_config.yml"
                metadata_key: "pcr_27"
            pcr_28:
                file: "pcr_config.yml"
                metadata_key: "pcr_28"
            pcr_29:
                file: "pcr_config.yml"
                metadata_key: "pcr_29"
            pcr_30:
                file: "pcr_config.yml"
                metadata_key: "pcr_30"
        npcr:
            name: "New Practical Chinese Reader Textbook, Vol 1 (by Zhang Kai, Liu Shehui, Chen Xi, Zuo Shandan, Shi Jiawei, Liu Xun)"
            npcr_01:
                file: "npcr_config.yml"
                metadata_key: "npcr_1"
            npcr_02:
                file: "npcr_config.yml"
                metadata_key: "npcr_2"
            npcr_03:
                file: "npcr_config.yml"
                metadata_key: "npcr_3"
            npcr_04:
                file: "npcr_config.yml"
                metadata_key: "npcr_4"
            npcr_05:
                file: "npcr_config.yml"
                metadata_key: "npcr_5"
            npcr_06:
                file: "npcr_config.yml"
                metadata_key: "npcr_6"
            npcr_07:
                file: "npcr_config.yml"
                metadata_key: "npcr_7"
            npcr_08:
                file: "npcr_config.yml"
                metadata_key: "npcr_8"
            npcr_09:
                file: "npcr_config.yml"
                metadata_key: "npcr_9"
            npcr_10:
                file: "npcr_config.yml"
                metadata_key: "npcr_10"
            npcr_11:
                file: "npcr_config.yml"
                metadata_key: "npcr_11"
            npcr_12:
                file: "npcr_config.yml"
                metadata_key: "npcr_12"
            npcr_13:
                file: "npcr_config.yml"
                metadata_key: "npcr_13"
            npcr_14:
                file: "npcr_config.yml"
                metadata_key: "npcr_14"
        pimsleur:
            name: "Pimsleur Mandarin Unit 1"
            pimsleur1_1:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur1_1"
            pimsleur1_2:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur1_2"
            pimsleur1_3:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur1_3"
            pimsleur1_4:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur1_4"
            pimsleur1_5:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur1_5"
            pimsleur1_6:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur1_6"
            pimsleur2_1:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur2_1"
            pimsleur2_2:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur2_2"
            pimsleur2_3:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur2_3"
            pimsleur2_4:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur2_4"
            pimsleur2_5:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur2_5"
            pimsleur2_6:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur2_6"
            pimsleur3_1:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur3_1"
            pimsleur3_2:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur3_2"
            pimsleur3_3:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur3_3"
            pimsleur3_4:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur3_4"
            pimsleur3_5:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur3_5"
            pimsleur3_6:
                file: "pimsleur_config.yml"
                metadata_key: "pimsleur3_6"
        schaums:
            name: ["Schaums’ Outlines Chinese Vocabulary (Yanping Xie, Duan-Duan Li)",1]
            schaums_asking_for_directions:
                file: "schaums_config.yml"
                metadata_key: "schaums_asking_for_directions"
            schaums_at_home:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_home"
            schaums_at_the_airport:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_the_airport"
            schaums_at_the_bank:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_the_bank"
            schaums_at_the_clothing_store:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_the_clothing_store"
            schaums_at_dry_cleaner:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_the_dry_cleaner"
            schaums_at_the_hospital:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_the_hospital"
            schaums_at_the_hotel:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_the_hotel"
            schaums_at_the_post_office:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_the_post_office"
            schaums_at_the_restaurant:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_the_restaurant"
            schaums_at_the_theater_and_the_movies:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_the_theater_and_the_movies"
            schaums_at_the_train_station:
                file: "schaums_config.yml"
                metadata_key: "schaums_at_the_train_station"
            schaums_the_weather:
                file: "schaums_config.yml"
                metadata_key: "schaums_the_weather"
            schaums_business:
                file: "schaums_config.yml"
                metadata_key: "schaums_business"
            schaums_computer_and_internet:
                file: "schaums_config.yml"
                metadata_key: "schaums_computer_and_internet"
            schaums_education:
                file: "schaums_config.yml"
                metadata_key: "schaums_education"
            schaums_making_a_phone_call:
                file: "schaums_config.yml"
                metadata_key: "schaums_making_a_phone_call"            
            schaums_on_the_airplane:
                file: "schaums_config.yml"
                metadata_key: "schaums_on_the_airplane"
            schaums_passport_control_and_customs:
                file: "schaums_config.yml"
                metadata_key: "schaums_passport_control_and_customs"
            schaums_public_transportation:
                file: "schaums_config.yml"
                metadata_key: "schaums_public_transportation"
            schaums_shopping_for_food:
                file: "schaums_config.yml"
                metadata_key: "schaums_shopping_for_food"
            schaums_sports:
                file: "schaums_config.yml"
                metadata_key: "schaums_sports"
            schaums_the_automobile:
                file: "schaums_config.yml"
                metadata_key: "schaums_the_automobile"
    frequency_bigrams:
        name: "Most Frequent Words (Bigrams)"
        frequency_1:
            file: "frequency_config.yml"
            metadata_key: "frequency_1"
        frequency_2:
            file: "frequency_config.yml"
            metadata_key: "frequency_2"
        frequency_3:
            file: "frequency_config.yml"
            metadata_key: "frequency_3"
        frequency_4:
            file: "frequency_config.yml"
            metadata_key: "frequency_4"
        frequency_5:
            file: "frequency_config.yml"
            metadata_key: "frequency_5"
        frequency_6:
            file: "frequency_config.yml"
            metadata_key: "frequency_6"
        frequency_7:
            file: "frequency_config.yml"
            metadata_key: "frequency_7"
    frequency:
        name: "Most Frequent Hànzì"
        frequency_1:
            file: "frequency_config.yml"
            metadata_key: "frequency_1"
        frequency_2:
            file: "frequency_config.yml"
            metadata_key: "frequency_2"
        frequency_3:
            file: "frequency_config.yml"
            metadata_key: "frequency_3"
        frequency_4:
            file: "frequency_config.yml"
            metadata_key: "frequency_4"
        frequency_5:
            file: "frequency_config.yml"
            metadata_key: "frequency_5"
        frequency_6:
            file: "frequency_config.yml"
            metadata_key: "frequency_6"
        frequency_7:
            file: "frequency_config.yml"
            metadata_key: "frequency_7"
    lwe_favs:
        file: "system_tags.yml"
        metadata_key: "lwe_favs"        
    starred_words:
        file: "system_tags.yml"
        metadata_key: "starred"
