#!/bin/sh

# First create the test data
echo "Running test merge on command line"
echo "Creating test data database w/ 3000 user history records and 50,000 card_id updates"
php makeTestUpdateSQL.php -n 50000 -o tmp_update_data.sql
php makeTestUserDataSQL.php -n 3000 -o tmp_user_data.sql

cat sql/beginTransaction tmp_update_data.sql sql/showDupes sql/commit > tmp_update_data.new.sql
rm tmp_update_data.sql
mv tmp_update_data.new.sql tmp_update_data.sql

# Make a fresh database
echo "Making fresh test database.."
cp jFlash-1.0.db jFlash.tmp.db
echo "Importing user data.."
sqlite3 jFlash.tmp.db < tmp_user_data.sql
echo "Starting update.."
sqlite3 jFlash.tmp.db < tmp_update_data.sql
rm tmp_update_data.sql
rm tmp_user_data.sql
