source 'http://rubygems.org'

gem 'rails', '3.0.9'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
 gem 'json'
 gem 'mechanize'
 gem 'nokogiri'

# Does not compile with Ruby 1.9. This can be substituted with gem Text.
# https://rubyforge.org/tracker/index.php?func=detail&aid=27462&group_id=6257&atid=24257
# http://procbits.com/2010/08/07/levenshtein-in-ruby-1-9/
# gem 'levenshtein'
gem 'text'

gem 'mysql2', '~> 0.2.6'
# gem 'base64'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
