source 'http://rubygems.org'
gem 'rails'
gem 'linecache19'
gem 'sqlite3'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
#gem 'ruby-debug'
gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
gem 'json'
gem 'mechanize'
gem 'nokogiri'

# Does not compile with Ruby 1.9. This can be substituted with gem Text.
# https://rubyforge.org/tracker/index.php?func=detail&aid=27462&group_id=6257&atid=24257
# http://procbits.com/2010/08/07/levenshtein-in-ruby-1-9/
# gem 'levenshtein'
gem 'text'
gem 'mysql'
gem 'mysql2'
gem 'columnize', '~> 0.3.5'

# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
